# $OpenBSD: Makefile,v 1.7 2021/02/19 20:44:45 edd Exp $

COMMENT=	powerful synthesizer engine with an interactive UI

PKGNAME=	zyn-fusion-3.0.5pre20210207

CATEGORIES=	audio meta

MAINTAINER=	Gagandeep Sawant <grsa32@gmail.com>

RUN_DEPENDS=	audio/zynaddsubfx \
		x11/mruby-zest

.include <bsd.port.mk>
